version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      nestjs:
        patterns:
          - '@nestjs/*'
      prisma:
        patterns:
          - 'prisma'
          - '@prisma/*'
      eslint:
        patterns:
          - 'eslint'
          - '@eslint/*'
          - 'typescript-eslint'
    open-pull-requests-limit: 10

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
